version: '2'

services:
  react_js:
    container_name: react_js_cuad
    build:
      context: .
      dockerfile: react.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./cuad-app:/usr/src/app/
    environment:
      - NODE_ENV=development